buildscript {
    ext {
        androidx_appcompat_version = "1.7.1"
        androidx_core_version = "1.16.0"
        // https://mvnrepository.com/artifact/androidx.exifinterface/exifinterface
        androidx_exifinterface_version = "1.4.1"
        // https://mvnrepository.com/artifact/androidx.transition/transition
        androidx_transition_version = "1.6.0"
        // https://mvnrepository.com/artifact/androidx.constraintlayout/constraintlayout
        constraintlayout_version = "2.1.4"
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // https://mvnrepository.com/artifact/com.android.tools.build/gradle
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

def isReleaseBuild() {
    return version.contains("SNAPSHOT") == false
}

allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        google()
        mavenCentral()
    }
}
