apply plugin: 'com.android.application'

android {
    namespace "com.yalantis.ucrop.sample"
    compileSdk 36
    defaultConfig {
        applicationId "com.yalantis.ucrop.sample"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 13
        versionName "1.2.4"
    }
    flavorDimensions "default"
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // region compile options

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    // endregion

    productFlavors {
        activity {
            buildConfigField("int","RequestMode", "1")
        }
        fragment {
            buildConfigField("int","RequestMode", "2")
        }
    }

    buildFeatures {
        buildConfig true
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.core:core:1.17.0"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    implementation "com.squareup.okhttp3:okhttp:5.1.0"
    implementation project(':ucrop')
}
