apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace "com.yalantis.ucrop"
    compileSdk 36
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // region compile options

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    // endregion

    sourceSets.main {
        jni.srcDirs = []
    }

    buildFeatures {
        buildConfig true
    }
    lint {
        abortOnError false
    }

    resourcePrefix 'ucrop_'
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.exifinterface:exifinterface:1.4.1"
    implementation "androidx.transition:transition:1.6.0"
    implementation "com.squareup.okhttp3:okhttp:5.1.0"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = "com.github.check24-profis"
                artifactId = "uCrop"
                version = VERSION_NAME
                artifact(bundleReleaseAar)
            }
        }
    }
}
