apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace "com.yalantis.ucrop"
    compileSdk 36
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        vectorDrawables.useSupportLibrary = true
        consumerProguardFiles 'consumer-rules.pro'
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // region compile options

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    // endregion


    resourcePrefix 'ucrop_'

    sourceSets.main {
        jni.srcDirs = []
    }

    buildFeatures {
        buildConfig true
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidx_appcompat_version}"
    implementation "androidx.exifinterface:exifinterface:${androidx_exifinterface_version}"
    implementation "androidx.transition:transition:${androidx_transition_version}"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = "com.github.check24-profis"
                artifactId = "uCrop"
                version = VERSION_NAME
                artifact(bundleReleaseAar)
            }
        }
    }
}
